(ns contemporary-words.core)

(def words [
  "a" "ah" "am" "an" "as" "at" "be" "by" "do" "go" "ha"
  "he" "hi" "if" "in" "is" "it" "me" "my" "no" "of" "oh"
  "on" "or" "so" "to" "up" "us" "we" "act" "add" "age"
  "ago" "aid" "aim" "air" "all" "and" "any" "are" "arm"
  "art" "ash" "ask" "ass" "ate" "awe" "bad" "bag" "bar"
  "bay" "bed" "bee" "beg" "bet" "bid" "big" "bit" "bow"
  "box" "boy" "bus" "but" "buy" "bye" "can" "cap" "car"
  "cat" "cop" "cry" "cup" "cut" "dad" "day" "dew" "did"
  "die" "dig" "dim" "dip" "dog" "dot" "dry" "due" "ear"
  "eat" "egg" "end" "eye" "fan" "far" "fat" "few" "fit"
  "fix" "fly" "foe" "fog" "for" "fry" "fun" "fur" "gas"
  "gay" "get" "god" "got" "gun" "gut" "guy" "gym" "had"
  "has" "hat" "her" "hey" "hid" "him" "hip" "his" "hit"
  "hmm" "hop" "hot" "how" "hug" "huh" "hum" "ice" "ill"
  "ink" "its" "jaw" "job" "jog" "joy" "key" "kid" "lap"
  "law" "lay" "led" "leg" "let" "lie" "lip" "lit" "lot"
  "low" "mad" "man" "map" "may" "men" "met" "mid" "mix"
  "mom" "mud" "mum" "new" "nod" "nor" "not" "now" "odd"
  "ode" "off" "old" "one" "our" "out" "own" "pad" "pat"
  "pay" "pen" "pet" "pie" "pig" "pin" "pit" "pop" "pot"
  "put" "ran" "raw" "ray" "red" "rid" "rip" "rot" "row"
  "rub" "run" "sad" "sat" "saw" "say" "sea" "see" "set"
  "sex" "she" "shy" "sin" "sip" "sir" "sit" "six" "sky"
  "sob" "son" "sun" "tan" "tap" "tea" "ten" "the" "thy"
  "tie" "tip" "toe" "too" "top" "toy" "try" "tug" "two"
  "use" "van" "war" "was" "way" "wet" "who" "why" "win"
  "won" "wow" "yea" "yep" "yes" "yet" "you" "able" "ache"
  "acid" "alas" "also" "area" "army" "aunt" "away" "baby"
  "back" "ball" "band" "bang" "bank" "bare" "bark" "base"
  "beam" "bear" "beat" "been" "beer" "bell" "belt" "bend"
  "bent" "best" "bike" "bill" "bind" "bird" "bite" "blew"
  "blow" "blue" "blur" "boat" "body" "bold" "bomb" "bond"
  "bone" "book" "boom" "boot" "bore" "born" "boss" "both"
  "bowl" "brow" "bump" "burn" "bury" "bush" "busy" "butt"
  "cage" "cake" "call" "calm" "came" "camp" "card" "care"
  "case" "cast" "cave" "cell" "chat" "chew" "chin" "chip"
  "city" "claw" "clay" "club" "clue" "coat" "cock" "cold"
  "come" "cook" "cool" "copy" "core" "cost" "crap" "cure"
  "curl" "cute" "damn" "dare" "dark" "dart" "dash" "date"
  "dawn" "dead" "deal" "dear" "deep" "deny" "desk" "dial"
  "dine" "dirt" "dish" "dive" "does" "doll" "done" "doom"
  "door" "dorm" "dove" "down" "drag" "draw" "drew" "drop"
  "drug" "drum" "duck" "dude" "dull" "dumb" "dump" "dust"
  "each" "ease" "easy" "echo" "edge" "else" "even" "ever"
  "evil" "exit" "face" "fact" "fade" "fail" "fair" "fake"
  "fall" "fast" "fate" "fear" "feed" "feel" "feet" "fell"
  "felt" "file" "fill" "film" "find" "fine" "fire" "fish"
  "fist" "five" "flag" "flat" "flaw" "flew" "flip" "flop"
  "flow" "fold" "food" "fool" "foot" "form" "foul" "four"
  "free" "from" "fuck" "full" "gain" "game" "gang" "gasp"
  "gate" "gave" "gaze" "gift" "girl" "give" "glad" "glow"
  "goal" "gold" "gone" "good" "grab" "grew" "grey" "grin"
  "grip" "grow" "gulp" "hair" "half" "hall" "hand" "hang"
  "hard" "harm" "hate" "have" "head" "heal" "hear" "heat"
  "heel" "held" "hell" "help" "here" "hero" "hers" "hide"
  "high" "hill" "hint" "hiss" "hold" "hole" "holy" "home"
  "hook" "hope" "hour" "howl" "huge" "hung" "hunt" "hurl"
  "hurt" "idea" "inch" "into" "iron" "jeep" "jerk" "jock"
  "join" "joke" "jump" "just" "keep" "kept" "kick" "kill"
  "kind" "king" "kiss" "knee" "knew" "know" "lace" "lack"
  "lady" "laid" "lake" "land" "last" "late" "lazy" "lead"
  "leaf" "lean" "leap" "left" "less" "lick" "life" "lift"
  "like" "limb" "line" "list" "live" "load" "lock" "long"
  "look" "lord" "lose" "loss" "lost" "loud" "love" "luck"
  "lung" "lust" "made" "main" "make" "male" "mall" "mama"
  "many" "mark" "mask" "mass" "mate" "math" "meal" "mean"
  "meet" "melt" "mend" "mere" "mess" "mile" "milk" "mind"
  "mine" "miss" "mist" "moan" "mock" "mold" "mood" "moon"
  "more" "most" "move" "much" "muse" "must" "nail" "name"
  "near" "neck" "need" "nerd" "next" "nice" "nine" "none"
  "nope" "nose" "note" "numb" "okay" "once" "only" "onto"
  "open" "over" "pace" "pack" "page" "paid" "pain" "pair"
  "pale" "palm" "park" "part" "pass" "past" "path" "peek"
  "peel" "peer" "pick" "pile" "pill" "pink" "piss" "pity"
  "plan" "play" "plus" "poem" "poet" "pool" "poor" "post"
  "pour" "pout" "pray" "puff" "pull" "pure" "push" "quit"
  "race" "rage" "rain" "rang" "rant" "rape" "rare" "read"
  "real" "rent" "rest" "rich" "ride" "ring" "rise" "risk"
  "road" "roam" "roar" "rock" "rode" "roll" "roof" "room"
  "root" "rope" "rose" "rude" "ruin" "rule" "rush" "safe"
  "said" "sail" "sake" "salt" "same" "sand" "sane" "save"
  "scan" "scar" "seal" "seat" "seed" "seek" "seem" "seen"
  "seep" "self" "sell" "send" "sent" "shed" "ship" "shit"
  "shoe" "shop" "shot" "show" "shut" "sick" "side" "sigh"
  "sign" "sing" "sink" "size" "skin" "skip" "slam" "slap"
  "slid" "slip" "slow" "slut" "snap" "snow" "soak" "soar"
  "sofa" "soft" "some" "song" "soon" "sore" "sort" "soul"
  "spat" "spin" "spit" "spot" "spun" "stab" "star" "stay"
  "step" "stir" "stop" "stun" "such" "suck" "suit" "sure"
  "sway" "swim" "tail" "take" "tale" "talk" "tall" "tank"
  "tape" "task" "team" "tear" "teen" "tell" "tend" "tent"
  "term" "test" "than" "that" "thee" "them" "then" "they"
  "thin" "this" "thou" "thus" "tick" "tide" "till" "tilt"
  "time" "tiny" "tire" "told" "tone" "took" "tool" "torn"
  "toss" "tour" "town" "trap" "tray" "tree" "trip" "true"
  "tuck" "tune" "turn" "twin" "type" "ugly" "upon" "urge"
  "vain" "vast" "veil" "vein" "very" "view" "void" "wait"
  "wake" "walk" "wall" "want" "warm" "warn" "wash" "wave"
  "weak" "wear" "week" "weep" "well" "went" "were" "west"
  "what" "when" "whip" "whom" "wide" "wife" "wild" "will"
  "wind" "wine" "wing" "wipe" "wise" "wish" "with" "woke"
  "wolf" "wood" "word" "wore" "work" "worn" "wrap" "yank"
  "yard" "yawn" "yeah" "year" "yell" "your" "about" "above"
  "abuse" "admit" "adore" "adult" "after" "again" "agony"
  "agree" "ahead" "alarm" "alive" "allow" "alone" "along"
  "alter" "amaze" "among" "amuse" "angel" "anger" "angry"
  "annoy" "apart" "apple" "argue" "arrow" "aside" "avoid"
  "await" "awake" "aware" "awful" "badly" "beach" "beard"
  "beast" "began" "begin" "begun" "belly" "below" "bench"
  "birth" "bitch" "black" "blade" "blame" "blank" "blast"
  "bleed" "blend" "bless" "blind" "blink" "bliss" "block"
  "blood" "bloom" "blush" "board" "bound" "brain" "brand"
  "brave" "bread" "break" "brief" "bring" "broke" "brown"
  "brush" "build" "built" "bunch" "burst" "cabin" "candy"
  "carry" "carve" "catch" "cause" "cease" "chain" "chair"
  "charm" "chase" "cheap" "cheat" "check" "cheek" "cheer"
  "chest" "child" "chill" "choke" "chose" "claim" "class"
  "clean" "clear" "click" "climb" "cling" "clock" "close"
  "cloud" "coach" "color" "couch" "cough" "could" "count"
  "court" "cover" "crack" "crash" "crave" "crawl" "crazy"
  "creak" "cream" "creek" "creep" "crime" "cross" "crowd"
  "crown" "cruel" "crush" "curse" "curve" "daddy" "daily"
  "dance" "death" "decay" "demon" "depth" "devil" "dirty"
  "doubt" "drama" "drawn" "dread" "dream" "dress" "drift"
  "drink" "drive" "drove" "drown" "drunk" "dusty" "dwell"
  "eager" "early" "earth" "eaten" "eight" "elbow" "empty"
  "enemy" "enjoy" "enter" "erase" "event" "every" "exact"
  "exist" "extra" "faint" "fairy" "faith" "false" "fancy"
  "fault" "favor" "feast" "fence" "field" "fifty" "fight"
  "final" "first" "flame" "flare" "flash" "flesh" "flick"
  "flirt" "float" "flood" "floor" "flush" "focus" "force"
  "forth" "forty" "found" "frame" "freak" "fresh" "front"
  "frost" "frown" "froze" "fruit" "fully" "funny" "ghost"
  "giant" "given" "glare" "glass" "glide" "glory" "glove"
  "gonna" "goose" "gotta" "grace" "grade" "grand" "grant"
  "grasp" "grass" "grave" "great" "green" "greet" "grief"
  "groan" "group" "growl" "grown" "grunt" "guard" "guess"
  "guest" "guide" "guilt" "habit" "happy" "harsh" "haunt"
  "hazel" "heard" "heart" "heavy" "hello" "honey" "honor"
  "horse" "hotel" "house" "human" "hurry" "idiot" "image"
  "inner" "issue" "jeans" "judge" "juice" "kinda" "knife"
  "knock" "known" "large" "laugh" "learn" "least" "leave"
  "level" "light" "limit" "local" "loose" "loser" "lover"
  "lower" "lucky" "lunch" "magic" "major" "march" "marry"
  "match" "maybe" "meant" "mercy" "metal" "might" "mommy"
  "money" "month" "moral" "mourn" "mouth" "movie" "music"
  "naked" "nerve" "never" "night" "noise" "north" "nurse"
  "occur" "ocean" "offer" "often" "order" "other" "owner"
  "paint" "panic" "pants" "paper" "party" "pause" "peace"
  "peach" "petal" "phone" "photo" "piece" "pitch" "pizza"
  "place" "plain" "plane" "plant" "plate" "plead" "point"
  "porch" "pound" "power" "press" "price" "pride" "proud"
  "prove" "pulse" "punch" "puppy" "purse" "queen" "quick"
  "quiet" "quite" "radio" "raise" "reach" "react" "ready"
  "rebel" "relax" "reply" "rhyme" "right" "river" "rough"
  "round" "royal" "sadly" "salty" "scale" "scare" "scary"
  "scene" "scent" "score" "scowl" "screw" "sense" "serve"
  "seven" "shade" "shake" "shall" "shame" "shape" "share"
  "sharp" "sheep" "sheet" "shell" "shift" "shine" "shiny"
  "shirt" "shock" "shook" "shoot" "shore" "short" "shout"
  "shove" "shown" "shrug" "sight" "silly" "since" "skill"
  "skirt" "sleep" "slept" "slice" "slide" "smack" "small"
  "smart" "smell" "smile" "smirk" "smoke" "snake" "sneak"
  "sniff" "snort" "sorry" "sound" "space" "spare" "speak"
  "speed" "spell" "spend" "spent" "spill" "spine" "split"
  "spoke" "sport" "stage" "stain" "stair" "stall" "stand"
  "stare" "start" "state" "steal" "steel" "stick" "still"
  "sting" "stock" "stole" "stone" "stood" "store" "storm"
  "story" "strap" "stray" "strip" "stuck" "study" "stuff"
  "style" "swear" "sweat" "sweep" "sweet" "swell" "swing"
  "swirl" "sword" "swung" "table" "taint" "taken" "taste"
  "teach" "tease" "teeth" "tense" "thank" "their" "there"
  "these" "thick" "thigh" "thing" "think" "third" "thorn"
  "those" "three" "threw" "throw" "thumb" "thump" "tight"
  "tired" "today" "topic" "total" "touch" "tough" "towel"
  "tower" "trace" "track" "trade" "trail" "train" "treat"
  "trick" "truck" "truly" "trust" "truth" "twice" "twirl"
  "twist" "uncle" "under" "until" "upset" "usual" "utter"
  "value" "verse" "video" "visit" "voice" "waist" "wanna"
  "waste" "watch" "water" "weary" "weave" "weird" "wheel"
  "where" "which" "while" "whine" "white" "whole" "whore"
  "whose" "widen" "wince" "witch" "woman" "women" "world"
  "worry" "worse" "worst" "worth" "would" "wound" "wrist"
  "write" "wrong" "wrote" "yearn" "young" "yours" "youth"
  "accent" "accept" "across" "action" "admire" "advice"
  "afraid" "almost" "always" "amount" "animal" "answer"
  "anyone" "anyway" "appear" "around" "arrive" "asleep"
  "assume" "assure" "attack" "autumn" "awaken" "awhile"
  "barely" "battle" "beaten" "beauty" "became" "become"
  "before" "behind" "belief" "belong" "beside" "better"
  "beyond" "bitter" "blonde" "bloody" "bother" "bottle"
  "bottom" "bought" "bounce" "branch" "breast" "breath"
  "breeze" "bridge" "bright" "broken" "bruise" "bubble"
  "bullet" "burden" "button" "calmly" "camera" "campus"
  "candle" "cannot" "canvas" "caress" "carpet" "caught"
  "center" "chance" "change" "charge" "cheese" "choice"
  "choose" "church" "circle" "clench" "closet" "clutch"
  "coffee" "collar" "commit" "common" "condom" "cookie"
  "corner" "couple" "course" "cousin" "coward" "create"
  "damage" "danger" "deadly" "decide" "deeply" "defeat"
  "define" "demand" "depend" "desert" "design" "desire"
  "detail" "dinner" "direct" "doctor" "dollar" "double"
  "dragon" "drawer" "driver" "during" "easily" "effect"
  "effort" "either" "emerge" "energy" "engine" "enough"
  "entire" "escape" "except" "excite" "excuse" "expect"
  "fairly" "fallen" "family" "famous" "father" "female"
  "figure" "finger" "finish" "firmly" "flight" "flower"
  "follow" "forest" "forget" "forgot" "former" "fought"
  "freely" "freeze" "friend" "fright" "frozen" "future"
  "garage" "garden" "gather" "gentle" "gently" "giggle"
  "glance" "golden" "gotten" "ground" "guilty" "guitar"
  "handle" "happen" "hardly" "hatred" "health" "heaven"
  "height" "hidden" "hollow" "honest" "horror" "hunger"
  "hungry" "hunter" "ignore" "indeed" "inform" "inhale"
  "insane" "inside" "insist" "insult" "invite" "itself"
  "jacket" "lately" "leader" "length" "lesson" "letter"
  "likely" "linger" "liquid" "listen" "little" "locker"
  "lonely" "loudly" "lovely" "makeup" "manage" "manner"
  "master" "matter" "melody" "member" "memory" "mental"
  "merely" "middle" "mighty" "minute" "mirror" "misery"
  "moment" "monkey" "mostly" "mother" "motion" "mumble"
  "murder" "murmur" "muscle" "mutter" "myself" "narrow"
  "nation" "nature" "nearby" "nearly" "needle" "nobody"
  "normal" "notice" "number" "object" "office" "option"
  "orange" "outfit" "parent" "pencil" "people" "period"
  "person" "pierce" "pillow" "planet" "player" "please"
  "plenty" "pocket" "poetry" "poison" "police" "ponder"
  "praise" "prayer" "prefer" "pretty" "prince" "public"
  "purple" "puzzle" "rabbit" "random" "rather" "really"
  "reason" "recall" "record" "refuse" "regret" "relief"
  "remain" "remark" "remind" "remove" "repeat" "report"
  "resist" "result" "retort" "return" "reveal" "rhythm"
  "ripple" "sanity" "savior" "school" "scrape" "scream"
  "screen" "search" "season" "second" "secret" "settle"
  "shadow" "shield" "shiver" "should" "shower" "shriek"
  "signal" "silent" "silver" "simple" "simply" "single"
  "sister" "sleeve" "slight" "slowly" "smooth" "snatch"
  "social" "softly" "soothe" "sorrow" "spider" "spiral"
  "spirit" "spoken" "spread" "spring" "square" "squeal"
  "steady" "stolen" "strain" "stream" "street" "stress"
  "strife" "strike" "string" "stroke" "strong" "struck"
  "stupid" "sudden" "suffer" "summer" "sunset" "supply"
  "surely" "switch" "system" "talent" "tangle" "taught"
  "tender" "terror" "thirty" "though" "thread" "throat"
  "throne" "thrown" "ticket" "tickle" "toilet" "tongue"
  "toward" "travel" "tumble" "twelve" "twenty" "unable"
  "unless" "unlike" "unseen" "valley" "velvet" "victim"
  "vision" "volume" "wander" "warmth" "weapon" "weight"
  "whilst" "window" "winter" "within" "wonder" "wooden"
  "yellow" "ability" "address" "against" "alcohol" "already"
  "alright" "ancient" "angrily" "another" "anybody" "anymore"
  "ashamed" "attempt" "awesome" "awkward" "balance" "bastard"
  "because" "bedroom" "believe" "beneath" "besides" "between"
  "blanket" "blossom" "breathe" "briefly" "brother" "brought"
  "captain" "capture" "careful" "ceiling" "certain" "chapter"
  "chicken" "chuckle" "clearly" "closely" "clothes" "collect"
  "college" "comfort" "command" "comment" "company" "compare"
  "concern" "confuse" "connect" "consume" "contact" "contain"
  "content" "control" "correct" "counter" "country" "courage"
  "creator" "crimson" "crumble" "crystal" "curious" "curtain"
  "darling" "defense" "delight" "depress" "descend" "deserve"
  "despair" "despite" "destroy" "diamond" "discuss" "disgust"
  "display" "distant" "disturb" "doorway" "dreamer" "embrace"
  "emotion" "endless" "essence" "eternal" "evening" "exactly"
  "examine" "example" "exclaim" "exhaust" "explain" "explode"
  "explore" "express" "eyebrow" "fantasy" "fashion" "feather"
  "feature" "fifteen" "finally" "flicker" "flutter" "forever"
  "forgive" "forward" "fragile" "freedom" "further" "general"
  "gesture" "goodbye" "grandma" "grimace" "grumble" "halfway"
  "hallway" "happily" "harmony" "heavily" "herself" "himself"
  "history" "holiday" "horizon" "however" "hundred" "husband"
  "imagine" "impress" "include" "inquire" "instant" "instead"
  "involve" "jealous" "journey" "kingdom" "kitchen" "leather"
  "library" "lightly" "luckily" "machine" "measure" "mention"
  "message" "million" "mistake" "monster" "morning" "mystery"
  "natural" "neither" "nervous" "nothing" "nowhere" "observe"
  "obvious" "officer" "opinion" "outside" "painful" "parents"
  "partner" "passion" "patient" "pattern" "perfect" "perhaps"
  "picture" "plastic" "popular" "possess" "prepare" "present"
  "pretend" "private" "problem" "proceed" "process" "project"
  "promise" "protect" "protest" "purpose" "quarter" "quickly"
  "quietly" "rainbow" "reality" "realize" "receive" "reflect"
  "release" "relieve" "replace" "respect" "respond" "retreat"
  "revenge" "sadness" "satisfy" "scatter" "scratch" "selfish"
  "serious" "service" "several" "shatter" "shelter" "shimmer"
  "shudder" "shuffle" "silence" "similar" "society" "soldier"
  "someday" "somehow" "someone" "special" "squeeze" "startle"
  "station" "stomach" "strange" "stretch" "student" "stumble"
  "subject" "suggest" "suicide" "support" "suppose" "surface"
  "survive" "suspect" "suspend" "swallow" "sweater" "teacher"
  "terrify" "thought" "through" "thunder" "tighten" "tightly"
  "tonight" "torment" "torture" "totally" "tremble" "trickle"
  "trouble" "uniform" "unknown" "useless" "usually" "various"
  "warrior" "weather" "wedding" "weekend" "welcome" "whether"
  "whisper" "whistle" "whoever" "without" "worship" "wrinkle"
  "written" "abruptly" "accident" "actually" "although"
  "announce" "anything" "anywhere" "approach" "argument"
  "attitude" "backpack" "backward" "bathroom" "birthday"
  "business" "casually" "children" "clothing" "collapse"
  "complain" "complete" "computer" "concrete" "consider"
  "constant" "continue" "convince" "corridor" "creation"
  "creature" "customer" "darkness" "daughter" "decision"
  "delicate" "describe" "directly" "discover" "disguise"
  "distance" "distract" "driveway" "elevator" "entirely"
  "entrance" "eternity" "everyday" "everyone" "exchange"
  "familiar" "favorite" "felicity" "football" "footstep"
  "forehead" "friendly" "frighten" "glorious" "gorgeous"
  "handsome" "hesitate" "homework" "honestly" "horrible"
  "hospital" "illusion" "innocent" "interest" "irritate"
  "language" "laughter" "lifeless" "magazine" "marriage"
  "mentally" "midnight" "mountain" "movement" "neighbor"
  "normally" "notebook" "opposite" "paradise" "pathetic"
  "patience" "peaceful" "personal" "physical" "pleasure"
  "position" "possible" "possibly" "powerful" "practice"
  "precious" "pregnant" "presence" "pressure" "previous"
  "princess" "probably" "question" "reaction" "recently"
  "remember" "response" "roommate" "sandwich" "schedule"
  "security" "sentence" "separate" "shoulder" "sidewalk"
  "silently" "slightly" "somebody" "sometime" "somewhat"
  "straight" "stranger" "strength" "struggle" "stubborn"
  "suddenly" "sunlight" "surprise" "surround" "sympathy"
  "teenager" "terrible" "thousand" "threaten" "together"
  "tomorrow" "treasure" "universe" "upstairs" "violence"
  "weakness" "whatever" "whenever" "yourself" "affection"
  "afternoon" "afterward" "agreement" "apartment" "apologize"
  "attention" "basically" "beautiful" "boyfriend" "breakfast"
  "butterfly" "cafeteria" "carefully" "certainly" "challenge"
  "character" "childhood" "chocolate" "cigarette" "classroom"
  "companion" "condition" "confusion" "dangerous" "desperate"
  "determine" "different" "difficult" "direction" "disappear"
  "disbelief" "embarrass" "emptiness" "everybody" "everytime"
  "existence" "expensive" "extremely" "forgotten" "frustrate"
  "happiness" "heartbeat" "hopefully" "ignorance" "important"
  "innocence" "instantly" "interrupt" "interview" "introduce"
  "invisible" "knowledge" "lightning" "moonlight" "necessary"
  "nervously" "nightmare" "obviously" "otherwise" "ourselves"
  "passenger" "perfectly" "principal" "recognize" "sanctuary"
  "seriously" "situation" "something" "sometimes" "somewhere"
  "statement" "suffocate" "wonderful" "worthless" "yesterday"
  "absolutely" "apparently" "appearance" "appreciate"
  "background" "completely" "confidence" "connection"
  "constantly" "definitely" "depression" "difference"
  "disappoint" "downstairs" "especially" "eventually"
  "everything" "everywhere" "excitement" "experience"
  "expression" "friendship" "generation" "girlfriend"
  "government" "illuminate" "impossible" "particular"
  "perfection" "reflection" "restaurant" "ridiculous"
  "straighten" "television" "themselves" "throughout"
  "underneath" "understand" "understood" "comfortable"
  "concentrate" "desperately" "destination" "frustration"
  "imagination" "immediately" "information" "opportunity"
  "practically" "conversation" "particularly" "relationship"
  "surprisingly" "sarcastically" "uncomfortable"
  "unfortunately"])

(let [l (count words)
      secure-random (java.security.SecureRandom.)]
  (defn random-word []
    (nth words (long (* l (.nextDouble secure-random))))
  )
)

(defn random-words
  ([n] (doall (repeatedly n random-word)))
  ([n sep] (clojure.string/join sep (random-words n))))
